---
title: "Data Workshop"
author: "Marina Kochuten"
format: html
editor_options: 
  chunk_output_type: console
---

# Writing Markdown Text

# Level 1 header

## Level 2 header

### level 3

#### level 4

**Bold text**

*Italic*

I can 

- Make
- A
- List

I can also link [super cool websites](https://restorationfund.org)

**To write code**

```{r}
2 + 2
```


```{r}
#| code-fold: true

# This code will only show up if you click on a dropdown to open it
2 + 2
```

```{r}
#| echo: false

# Your code will not show at all, only the output
2 + 2
```

```{r}
#| include: false

# This code will run, but neither the code nor the output will render
2 + 2
```

# Penguins Analysis

## About

Purpose of this script

something about the data


## Setup

```{r}
# Load libraries ----
library(tidyverse)
library(here)
library(janitor)
library(lubridate) # for date times
library(gghighlight)
library(sysfonts)
library(showtext)

# Read in data ----
penguins_raw <- read_csv(here("data", "raw", "messy_penguins.csv"))
nesting_raw <- read_csv(here("data", "raw", "nesting.csv"))
```


## Data exploration

```{r}
# What columns are in the penguins data?
colnames(penguins_raw)

# How many penguin species?
n_distinct(penguins_raw$Species)

# What are they?
unique(penguins_raw$Species)

# What islands?
unique(penguins_raw$island)
```

## Data Cleaning

```{r}
# Peek at the data
head(penguins_raw)
```

```{r}
# Clean up column names
penguins_clean <- penguins_raw |>
  clean_names()

# Check columns fix
colnames(penguins_clean)
```

```{r}
# Island column ----

# Fix inconsistent capitalization in the island col
penguins_clean <- penguins_clean |>
  mutate(island = str_to_title(island))

# Check
unique(penguins_clean$island)
```

```{r}
# Bill length column ----

range(penguins_clean$bill_length_mm, na.rm = TRUE)

class(penguins_clean$bill_length_mm)

# What values are not numeric?
penguins_clean |>
  count(bill_length_mm) |>
  filter(is.na(as.numeric(bill_length_mm)))

penguins_clean <- penguins_clean |>
  mutate(bill_length_mm = as.numeric(bill_length_mm))

# Check range
range(penguins_clean$bill_length_mm, na.rm = TRUE)

penguins_clean <- penguins_clean |>
  mutate(bill_length_mm = case_when(bill_length_mm == -999.0 ~ NA,
                                    .default = bill_length_mm))

# Check range
range(penguins_clean$bill_length_mm, na.rm = TRUE)
```

```{r}
# Observation date column ----
head(penguins_clean$observation_date)

# Fix datetime
penguins_clean <- penguins_clean |>
  mutate(date = parse_date_time(observation_date,
                                orders = c("dmy", "ymd", "mdy",
                                           "ymd HMS")))

head(penguins_clean$date)

# Do not need time
penguins_clean <- penguins_clean |>
  separate(col = date,
           into = c("date", "time"),
           sep = " ") |>
  mutate(date = as.Date(date))
 
# Drop columns we don't need
penguins_clean <- penguins_clean |>
  select(-c(time, observation_date))

# Create some new variables based on date
penguins_clean <- penguins_clean |>
  mutate(year = year(date),
         month = month(date, label = TRUE, abbr = FALSE),
         day = day(date),
         day_of_year = yday(date))
```

```{r}
# Check duplicates
penguins_clean |>
  get_dupes()
```

```{r}
# Remove the duplicates (I talked with the fieldies!!)
# Count rows before removing
nrow(penguins_clean)

# Remove dupes
penguins_clean <- penguins_clean |>
  distinct()

# Count after removing
nrow(penguins_clean)
```

```{r}
# Save cleaned penguin data ----
write_csv(penguins_clean, here("data", "processed", "penguins.csv"))
```


## Visualization

```{r}
# Simple bar chart
pen_bar <- ggplot(penguins_clean |>
         mutate(species = fct_rev(fct_infreq(species)))) +
  geom_bar(aes(x = species)) +
  geom_text(aes(x = species, label = after_stat(count)),
            stat = "count",
            hjust = 1.5,
            color = "white",
            size = 5) +
  labs(title = "Penguin counts at Palmer Station LTER",
       subtitle = "2007 - 2009",
       caption = "Data: Gorman et al. 2014 via {palmerpenguins}") +
  coord_flip() +
  theme_minimal(base_size = 14) +
  theme(
    axis.title = element_blank(),
    axis.text.x = element_blank(),
    panel.grid = element_blank(),
    plot.caption = element_text(face = "italic",
                                color = "grey50",
                                size = rel(0.7)),
    plot.title.position = "plot",
    plot.title = element_text(face = "bold"),
    plot.margin = margin(20, 20, 20, 20)
  )
```

```{r}
# Save beautiful penguins bar chart
# ggsave(here("figs", "pen_bar.png"),
#        pen_bar, width = 6, height = 4)
```

```{r}
# Penguin size scatterplot
pen_size_annot <- ggplot(data = penguins_clean,
       aes(x = bill_length_mm,
                 y = bill_depth_mm,
                 color = species)) +
  geom_point(aes(shape = species),
             size = 3,
             alpha = 0.8) +
  geomtextpath::geom_labelsmooth(aes(label = species),
                                 method = "lm",
                                 size = 5,
                                 linewidth = 1) +
  # geom_smooth(method = "lm", se = FALSE) +
  scale_color_manual(values = c("darkorange", 
                                "purple",
                                "cyan4")) +
  labs(title = "Penguin bill dimensions",
       subtitle = "Bill length and depth for Adelie, Chinstrap, and Gentoo penguins at Palmer Station LTER",
       x = "Bill length (mm)",
       y = "Bill depth (mm)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme_minimal(base_size = 14) +
  theme(
    plot.title.position = "plot",
    plot.margin = margin(10, 10, 10, 10),
    axis.title.x = element_text(margin = 
                                  margin(15, 0, 0, 0)),
    axis.title.y = element_text(margin = 
                                 margin(0,15, 0, 0)), 
    plot.title = element_text(face = "bold"),
    legend.position = "none"
  )

```

```{r}
# Save ----
ggsave(here("figs", "pen_size_annot.png"),
       pen_size_annot, width = 12, height = 8)
```














